import crypto from 'crypto';
import fs from 'fs';
import { createLogger } from './logger';
import { storeExcalidrawView } from './excalidraw-views';
import type { ArtifactData } from '../../src/types';

const logger = createLogger('artifact-detector');

// ---- Tool name matching ----

function isExcalidrawTool(name: string): boolean {
  const lower = name.toLowerCase();
  return lower.includes('excalidraw') && (
    lower.endsWith('create_view') ||
    lower.endsWith('export_to_excalidraw') ||
    lower.endsWith('save_checkpoint')
  );
}

// ---- .excalidraw file builder ----

function buildExcalidrawFile(elements: unknown[], appState: Record<string, unknown>): string {
  return JSON.stringify({
    type: 'excalidraw',
    version: 2,
    source: 'lionclaw',
    elements,
    appState: {
      gridSize: null,
      viewBackgroundColor: '#ffffff',
      ...appState,
    },
    files: {},
  }, null, 2);
}

// ---- Element extraction from tool input ----

function extractElements(input: Record<string, unknown>): {
  elements: unknown[];
  appState: Record<string, unknown>;
  title: string;
} | null {
  let rawElements: unknown[] | null = null;
  let appState: Record<string, unknown> = {};

  if (Array.isArray(input.elements)) {
    rawElements = input.elements;
    appState = (input.appState as Record<string, unknown>) || {};
  } else if (typeof input.elements === 'string') {
    try {
      const parsed = JSON.parse(input.elements);
      if (Array.isArray(parsed)) {
        rawElements = parsed;
        appState = (input.appState as Record<string, unknown>) || {};
      }
    } catch { /* ignore */ }
  } else if (typeof input.content === 'string') {
    try {
      const parsed = JSON.parse(input.content);
      if (Array.isArray(parsed.elements)) {
        rawElements = parsed.elements;
        appState = parsed.appState || {};
      } else if (Array.isArray(parsed)) {
        rawElements = parsed;
      }
    } catch { /* ignore */ }
  } else if (Array.isArray(input.content)) {
    rawElements = input.content;
  }

  if (!rawElements || rawElements.length === 0) return null;

  const title = (input.title as string) || (input.name as string) || 'Excalidraw';
  return { elements: rawElements, appState, title };
}

// ---- Public API ----

export function captureToolUse(
  toolUseId: string,
  toolName: string,
  input: Record<string, unknown>,
): ArtifactData | null {
  logger.info({ toolUseId, toolName }, 'captureToolUse called');

  if (!isExcalidrawTool(toolName)) return null;

  const extracted = extractElements(input);
  if (!extracted) {
    logger.warn(
      { toolName, inputKeys: Object.keys(input) },
      'Excalidraw tool detected but no elements found in input',
    );
    return null;
  }

  const viewId = crypto.randomUUID();

  // Store view data for the protocol handler to serve
  storeExcalidrawView(viewId, {
    elements: extracted.elements,
    appState: extracted.appState,
    title: extracted.title,
  });

  const excalidrawFile = buildExcalidrawFile(extracted.elements, extracted.appState);

  logger.info(
    { toolName, viewId, elementCount: extracted.elements.length, title: extracted.title },
    'Excalidraw artifact created',
  );

  return {
    id: viewId,
    type: 'mcp_app',
    title: extracted.title,
    toolName,
    data: {
      viewId,
      excalidrawFile,
    },
  };
}

export function captureToolResult(
  _toolUseId: string,
  content: string,
  isError: boolean,
): ArtifactData | null {
  if (isError) return null;

  // Detect image files generated by Nano Banana MCP
  // Path must start with / (unix) or X:\ (windows) to avoid matching explanatory text
  const imageMatch = content.match(/ARQUIVO_IMAGEM:\s*((?:\/|[A-Za-z]:\\).+?)(?:\n|$)/);
  if (imageMatch) {
    const imagePath = imageMatch[1].trim();
    try {
      const imageBuffer = fs.readFileSync(imagePath);
      const imageBase64 = imageBuffer.toString('base64');
      const ext = imagePath.toLowerCase().endsWith('.png') ? 'png' : 'jpg';
      const mimeType = ext === 'png' ? 'image/png' : 'image/jpeg';

      // Extract prompt from content
      const promptMatch = content.match(/Prompt:\s*(.+?)(?:\n|$)/);
      const prompt = promptMatch ? promptMatch[1].trim() : 'Imagem gerada';

      logger.info({ imagePath, sizeBytes: imageBuffer.length }, 'Image file read successfully for artifact');
      return {
        id: crypto.randomUUID(),
        type: 'image',
        title: `Imagem: ${prompt.substring(0, 50)}`,
        toolName: 'nano-banana',
        data: {
          imageBase64,
          mimeType,
          prompt,
          filePath: imagePath,
        },
      };
    } catch (err) {
      logger.warn({ imagePath, err }, 'Image file could not be read for artifact');
    }
  }

  // Detect audio files generated by ElevenLabs MCP
  // Path must start with / (unix) or X:\ (windows) to avoid matching explanatory text
  const audioMatch = content.match(/ARQUIVO_AUDIO:\s*((?:\/|[A-Za-z]:\\).+?)(?:\n|$)/);
  if (audioMatch) {
    const audioPath = audioMatch[1].trim();
    try {
      const audioBuffer = fs.readFileSync(audioPath);
      const audioBase64 = audioBuffer.toString('base64');
      logger.info({ audioPath, sizeBytes: audioBuffer.length }, 'Audio file read successfully for artifact');
      return {
        id: crypto.randomUUID(),
        type: 'audio',
        title: 'Audio gerado',
        toolName: 'elevenlabs',
        data: {
          audioBase64,
          mimeType: 'audio/mpeg',
          filePath: audioPath,
        },
      };
    } catch (err) {
      logger.warn({ audioPath, err }, 'Audio file could not be read for artifact -- check path exists and is accessible');
    }
  }

  return null;
}

export function resetArtifactDetector(): void {
  // No-op
}
